import Script from "next/script";
import Navbar from "./components/common/Navbar";
import { Chatbot } from '../components/shared/Chatbot';
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google"; // Import the font here
import ToastProvider from "./components/common/ToastProvider";
import Footer from "./components/common/Footer";
import SessionTimeout from "../(auth)/login/components/SessionTimeout";
import "../globals.css";

// Configure the font
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jakarta", // Create a CSS variable
});

export const metadata: Metadata = {
  title: "Mindsettler| Heal Your Mind and Soul",
  description: "Generated by team Frostbyte",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Apply the font variable and className to body */}
      <body className={`${jakarta.variable} font-sans antialiased bg-slate-50 text-slate-900`}>
        <Navbar />
        <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer@latest/dist/model-viewer.min.js"
          strategy="beforeInteractive"
        />
        <SessionTimeout />
        <ToastProvider />
        {children}
        <Chatbot />
        <Footer />
      </body>
    </html>
  );
}